import express from "express";
import { CategoryDistController } from "../controllers/CategoryDistController";
const router = express.Router();
const controller = new CategoryDistController();
router.get("/", controller.getFilter.bind(controller));
router.get("/:id", controller.getById.bind(controller));
router.post("/", controller.create.bind(controller));
router.put("/:id", controller.update.bind(controller));
router.delete("/:id", controller.remove.bind(controller));
export default router;
